openapi: 3.0.0
paths:
  /api/tvapp/device/users:
    get:
      operationId: TvDeviceController_getUserListByTvApp
      summary: tv에 등록된 유저 가져오기
      description: tv deviceToken으로 등록된 유저 리스트 가져오기
      parameters:
        - name: tvType
          required: false
          in: query
          description: tv 타입
          schema:
            type: string
        - name: deviceToken
          required: true
          in: query
          description: tv 기기 토큰
          schema:
            type: string
      responses:
        "200":
          description: get user list successfully
          content:
            application/json:
              example:
                statusCode: 200
                data:
                  users: "{유저 리스트}"
                isSuccess: true
                message: success
        "400":
          description: bad request
          content:
            application/json:
              example:
                statusCode: 400
                isSuccess: false
                message: "{에러 내용}"
      tags:
        &a1
        - Device
      security:
        &a2
        - bearer: []
  "/api/tvapp/device/disconnect/user/{id}":
    post:
      operationId: TvDeviceController_disconnectUserInTv
      summary: tv에 등록된 유저 해제하기
      description: 유저 해제하기
      parameters:
        - name: id
          required: true
          in: path
          description: user pk
          schema:
            type: number
        - name: tvType
          required: false
          in: query
          description: tv 타입
          schema:
            type: string
        - name: deviceToken
          required: true
          in: query
          description: tv 기기 토큰
          schema:
            type: string
      responses:
        "200":
          description: Disconnecting user successfully
          content:
            application/json:
              example:
                statusCode: 200
                isSuccess: true
                message: success
        "400":
          description: bad request
          content:
            application/json:
              example:
                statusCode: 400
                isSuccess: false
                message: "{에러 내용}"
      tags: *a1
      security: *a2
  /api/tvapp/auth/certCode:
    get:
      operationId: TvAuthController_getCerCode
      summary: 인증코드 가져오기
      parameters:
        - name: tvType
          required: false
          in: query
          description: tv 타입
          schema:
            type: string
        - name: deviceToken
          required: true
          in: query
          description: tv 기기 토큰
          schema:
            type: string
      responses:
        "200":
          description: get certCode successfully
          content:
            application/json:
              example:
                statusCode: 200
                data:
                  certCode: "{인증코드}"
                isSuccess: true
                message: success
        "400":
          description: bad request
          content:
            application/json:
              example:
                statusCode: 400
                isSuccess: false
                message: "{에러 내용}"
      tags:
        &a3
        - Auth
      security:
        &a4
        - bearer: []
  /api/tvapp/auth/check:
    get:
      operationId: TvAuthController_checkAuth
      summary: 서비스 연결 확인
      description: tv앱과 서비스 연결 되었는지 확인
      parameters:
        - name: tvType
          required: false
          in: query
          description: tv 타입
          schema:
            type: string
        - name: deviceToken
          required: true
          in: query
          description: tv 기기 토큰
          schema:
            type: string
      responses:
        "200":
          description: Check whether a connection is established or not
          content:
            application/json:
              example:
                statusCode: 200
                isSuccess: true
                message: 서비스가 연결되었습니다.
        "400":
          description: bad request
          content:
            application/json:
              example:
                statusCode: 400
                isSuccess: false
                message: "{에러 내용}"
      tags: *a3
      security: *a4
  /api/tvapp/test/fcm:
    get:
      operationId: TvTestController_getUserListByTvApp
      summary: fcm TEST
      parameters:
        - name: eventType
          required: true
          in: query
          description: 이벤트 타입(일반,중요,광고)
          schema:
            enum:
              - normal
              - important
              - advertise
              - important.advertise
            type: string
        - name: deviceToken
          required: true
          in: query
          description: tv 기기 토큰
          schema:
            type: string
      responses:
        "200":
          description: push data
          content:
            application/json:
              example:
                statusCode: 200
                isSuccess: true
                message: success
                data:
                  position: center
                  imageUrl: https://mars-sequel.s3.ap-northeast-2.amazonaws.com/images/car-collision+1.png
                  subMessage: 씽크웨이
                  redirectUrl: https://www.naver.com
                  title: 차량 알림
                  body: 마이카 알람서비스로부터 사고감지 알람이 도착했습니다.
                  type: normal
        "400":
          description: Bad Request
      tags:
        - Test
      security:
        - bearer: []
info:
  title: MyCarService TvApp API
  description: MyCarService TvApp API Description
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas: {}
